name: cclh
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  socket_io_client: ^3.0.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/cclh_logo.png"  
  windows:
    generate: true
    image_path: "assets/images/cclh_logo.png"
    icon_size: 48 # min:48, max:256, default: 48

flutter:
  uses-material-design: true
